secrets:
  variableNames:
    - CERT
    - KEY
    - CA
    # - PWD

iamRoleStatements:
  Effect: Allow
  Action:
    - secretsmanager:GetSecretValue
  Resource:
    - Ref: Secrets

resources:
  Resources:
    Secrets:
      Type: AWS::SecretsManager::Secret
      Properties: 
        Name: ${self:service}/${opt:stage}
