iamRoleStatements:
  Effect: Allow
  Action:
    - sns:Subscribe
    - sns:Unsubscribe
  Resource:
    Ref: Topic

resources:
  Resources:
    Topic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${opt:stage}
        # KmsMasterKeyId: alias/aws/sns

  Outputs:
    Topic:
      Value:
        Ref: Topic
