resources:
  Resources:
    DatadogAWSIntegrationPolicy: 
      Type: AWS::IAM::ManagedPolicy
      Condition: IsEast
      Properties:
        # PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${aws:accountId}:policy/${self:custom.subsys}-boundary-${opt:stage}'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            Action:
              - 'apigateway:GET'
              - 'autoscaling:Describe*'
              # - 'budgets:ViewBudget'
              # - 'cloudfront:GetDistributionConfig'
              # - 'cloudfront:ListDistributions'
              - 'cloudtrail:DescribeTrails'
              - 'cloudtrail:GetTrailStatus'
              - 'cloudtrail:LookupEvents'
              - 'cloudwatch:Describe*'
              - 'cloudwatch:Get*'
              - 'cloudwatch:List*'
              # - 'codedeploy:List*'
              # - 'codedeploy:BatchGet*'
              # - 'directconnect:Describe*'
              - 'dynamodb:List*'
              - 'dynamodb:Describe*'
              - 'ec2:Describe*'
              # - 'ecs:Describe*'
              # - 'ecs:List*'
              # - 'elasticache:Describe*'
              # - 'elasticache:List*'
              # - 'elasticfilesystem:DescribeFileSystems'
              # - 'elasticfilesystem:DescribeTags'
              - 'elasticloadbalancing:Describe*'
              # - 'elasticmapreduce:List*'
              # - 'elasticmapreduce:Describe*'
              - 'es:ListTags'
              - 'es:ListDomainNames'
              - 'es:DescribeElasticsearchDomains'
              - 'health:DescribeEvents'
              - 'health:DescribeEventDetails'
              - 'health:DescribeAffectedEntities'
              - 'kinesis:List*'
              - 'kinesis:Describe*'
              - 'lambda:GetPolicy'
              - 'lambda:List*'
              - 'lambda:RemovePermission'
              - 'logs:Get*'
              - 'logs:Describe*'
              - 'logs:FilterLogEvents'
              - 'logs:TestMetricFilter'
              - 'logs:PutSubscriptionFilter'
              - 'logs:DeleteSubscriptionFilter'
              - 'logs:DescribeSubscriptionFilters'
              - 'organizations:DescribeOrganization'
              - 'rds:Describe*'
              - 'rds:List*'
              # - 'redshift:DescribeClusters'
              # - 'redshift:DescribeLoggingStatus'
              # - 'route53:List*'
              - 's3:GetBucketLogging'
              - 's3:GetBucketLocation'
              - 's3:GetBucketNotification'
              - 's3:GetBucketTagging'
              - 's3:ListAllMyBuckets'
              - 's3:PutBucketNotification'
              - 'ses:Get*'
              - 'sns:List*'
              # - 'sns:Publish'
              # - 'sns:Subscribe'
              - 'sqs:ListQueues'
              - 'support:*'
              - 'tag:GetResources'
              - 'tag:GetTagKeys'
              - 'tag:GetTagValues'
              # - 'xray:BatchGetTraces'
              # - 'xray:GetTraceSummaries'
            Effect: Allow
            Resource: '*'

    # DatadogUser: 
    #   Type: AWS::IAM::User
    #   Condition: IsEast
    #   Properties:
    #     ManagedPolicyArns:
    #       - Ref: DatadogAWSIntegrationPolicy 

    # DatadogAWSIntegrationRole:
    #   Type: AWS::IAM::Role
    #   Condition: IsEast
    #   Properties: 
    #     # PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${aws:accountId}:policy/${self:custom.subsys}-boundary-${opt:stage}'
    #     RoleName: DatadogAWSIntegrationRole
    #     AssumeRolePolicyDocument:
    #       Statement:
    #         Effect: Allow
    #         Principal:
    #           AWS: arn:aws:iam::${self:custom.accounts.${opt:acct}.accountNumber}:root
    #         Action: sts:AssumeRole
    #         Condition:
    #           StringEquals:
    #             sts:ExternalId: <copy value from datadog aws integration dialog>
    #     ManagedPolicyArns:
    #       - Ref: DatadogAWSIntegrationPolicy
  