# this is the permission boundary policy
# that all service roles must attach
# this policy is refereneced in a service's serverless/iam.yml file
resources:
  Resources:
    ServerlessRuntimeBoundary: 
      Type: AWS::IAM::ManagedPolicy
      Condition: IsWest
      Properties:
        ManagedPolicyName: ${self:custom.subsys}-boundary-${opt:stage}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            # https://github.com/aws-samples/example-permissions-boundary
            - Effect: Allow
              Action:
                # - 'acm:GetC*'
                # - 'acm:ListC*'
                # - 'appsync:*'
                - 'athena:B*'
                - 'athena:CreateN*'
                - 'athena:DeleteN*'
                - 'athena:G*'
                - 'athena:L*'
                - 'athena:S*'
                # - 'cloudformation:DescribeStacks'
                - 'cloudwatch:PutMetricD*'
                - 'cloudwatch:PutMetricS*'
                - 'dynamodb:B*'
                - 'dynamodb:Co*'
                - 'dynamodb:DeleteI*'
                - 'dynamodb:DescribeS*'
                - 'dynamodb:DescribeTable'
                - 'dynamodb:G*'
                - 'dynamodb:ListG*'
                - 'dynamodb:ListS*'
                - 'dynamodb:ListT*'
                - 'dynamodb:Pa*'
                - 'dynamodb:Put*'
                - 'dynamodb:Q*'
                - 'dynamodb:Sc*'
                - 'dynamodb:UpdateI*'
                - 'ec2:Des*'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:AssignPrivateIpAddresses'
                - 'ec2:UnassignPrivateIpAddresses'
                - 'es:*'
                - 'events:ListEventB*'
                - 'events:PutE*'
                - 'events:PutPa*'
                - 'execute-api:*'
                - 'firehose:*'
                - 'glue:*'
                - 'kinesis:*'
                - 'kms:Dec*'
                - 'kms:Enc*'
                - 'kms:GenerateD*'
                - 'kms:GenerateR*'
                - 'kms:ListA*'
                - 'kms:ListKeys'
                - 'kms:ReE*'
                - 'kms:Si*'
                - 'kms:Verify'
                - 'lambda:InvokeA*'
                - 'lambda:InvokeFunction'
                - 'logs:CreateLogG*'
                - 'logs:CreateLogS*'
                - 'logs:Des*'
                - 'logs:F*'
                - 'logs:L*'
                - 'logs:PutL*'
                # - 'rds-db:*'
                - 's3:A*'
                - 's3:CreateJ*'
                - 's3:DeleteJ*'
                - 's3:DeleteO*'
                - 's3:DeleteStorageLensConfigurationT*'
                - 's3:DescribeJ*'
                - 's3:GetBucketLoc*'
                - 's3:GetE*'
                - 's3:GetL*'
                - 's3:GetObject'
                - 's3:GetObjectAc*'
                - 's3:GetObjectT*'
                - 's3:GetObjectVersion'
                - 's3:GetObjectVersionAc*'
                - 's3:GetObjectVersionF*'
                - 's3:GetObjectVersionT*'
                - 's3:L*'
                - 's3:PutBucketT*'
                - 's3:PutJ*'
                - 's3:PutL*'
                - 's3:PutObject'
                - 's3:PutObjectA*'
                - 's3:PutObjectT*'
                - 's3:PutObjectVersionT*'
                - 's3:PutStorageLensConfigurationT*'
                - 's3:ReplicateO*'
                - 's3:ReplicateT*'
                - 's3:Res*'
                - 's3:U*'
                - 'secretsmanager:Ca*'
                - 'secretsmanager:Des*'
                - 'secretsmanager:GetRa*'
                - 'secretsmanager:GetS*'
                - 'secretsmanager:L*'
                - 'secretsmanager:PutS*'
                - 'secretsmanager:Res*'
                - 'secretsmanager:Ro*'
                - 'secretsmanager:Up*'
                - 'ses:CreateCu*'
                - 'ses:CreateEmailT*'
                - 'ses:CreateT*'
                - 'ses:DeleteCu*'
                - 'ses:DeleteEmailT*'
                - 'ses:DeleteT*'
                - 'ses:GetCu*'
                - 'ses:GetEmailT*'
                - 'ses:GetIdentityV*'
                - 'ses:GetT*'
                - 'ses:ListCu*'
                - 'ses:ListEmailT*'
                - 'ses:ListTe*'
                - 'ses:Sen*'
                - 'ses:Te*'
                - 'ses:UpdateCu*'
                - 'ses:UpdateEmailT*'
                - 'ses:UpdateT*'
                - 'ses:VerifyEmailI*'
                - 'sns:CreateT*'
                - 'sns:ListSubscriptionsB*'
                - 'sns:ListTo*'
                - 'sns:P*'
                - 'sns:SetT*'
                - 'sns:Su*'
                - 'sqs:Ch*'
                - 'sqs:DeleteM*'
                - 'sqs:G*'
                - 'sqs:ListQueues'
                - 'sqs:P*'
                - 'sqs:Rec*'
                - 'sqs:Sen*'
                - 'ssm:DescribePar*'
                - 'ssm:GetPar*'
                - 'ssm:PutP*'
                - 'ssmmessages:*'
                # - 'states:DescribeA*'
                # - 'states:DescribeE*'
                # - 'states:GetA*'
                # - 'states:ListA*'
                # - 'states:ListE*'
                # - 'states:ListS*'
                # - 'states:S*'
                # - 'timestream:Ca*'
                # - 'timestream:ListD*'
                # - 'timestream:ListTab*'
                # - 'timestream:S*'
                # - 'timestream:W*'
                - 'xray:PutT*'
              Resource: '*'

  Outputs:
    ServerlessRuntimeBoundaryArn:
      Condition: IsWest
      Value:
        Ref: ServerlessRuntimeBoundary
